version: '2'

services:
  grafana:
    image: grafana/grafana-oss:8.1.5
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
    external: true
