id: Apache-Path-Traversal-Workflow
info:
  name: Apache Path Traversal Workflow
  author: EBB

workflows:
  - template: cve-2021-41773_path_traversal.yaml
  - template: cve-2021-41773_rce.yaml
  - template: cve-2021-42013_path_traversal.yaml
  - template: cve-2021-42013_rce.yaml
